### ISSUE TITLE
[Feature Request] Support angle in gradient

### ISSUE THREAD

**Issue by thewashingtonhua** [unsplash/react-trend#22]
currently gradient can only be vertical. is it possible to make it support custom angles ?

**Comment by joshwcomeau** [comment]
Hm, yeah, that would be pretty easy to add.

Unfortunately, this project isn't under active development anymore (@samijaber and I will likely continue to maintain it in the sense of making sure it works with newer versions of React, but I don't think either of us have the time to add features).

If you wanted to add it yourself, you could fork this project and then change the values [here](https://github.com/unsplash/react-trend/blob/master/src/components/Trend/Trend.js#L83). SVG gradients are kinda weird, in that you specify two points instead of specifying an angle, but it has the same effect.

Hope it helps!
